"""add birth_date to players

Revision ID: 0109d01ea83d
Revises: 754dc8c4172f
Create Date: 2026-06-13 23:35:03.147500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0109d01ea83d'
down_revision: Union[str, Sequence[str], None] = '754dc8c4172f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'birth_date')
    # ### end Alembic commands ###
