"""add player_valuations table

Revision ID: 6c3a96f3cc28
Revises: 0109d01ea83d
Create Date: 2026-07-20 23:14:15.365309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c3a96f3cc28'
down_revision: Union[str, Sequence[str], None] = '0109d01ea83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_valuations',
    sa.Column('nhl_id', sa.Integer(), nullable=False),
    sa.Column('fpts_per_game', sa.Float(), nullable=False),
    sa.Column('avg_toi', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('upside_score', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('game_forecasts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nhl_id'], ['players.nhl_id'], ),
    sa.PrimaryKeyConstraint('nhl_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_valuations')
    # ### end Alembic commands ###
