"""add team_rosters table

Revision ID: 71b2c6362b26
Revises: 6c3a96f3cc28
Create Date: 2026-07-24 17:23:09.750011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b2c6362b26'
down_revision: Union[str, Sequence[str], None] = '6c3a96f3cc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_key', sa.String(length=50), nullable=False),
    sa.Column('team_key', sa.String(length=50), nullable=False),
    sa.Column('nhl_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nhl_id'], ['players.nhl_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roster_league_player', 'team_rosters', ['league_key', 'nhl_id'], unique=True)
    op.create_index('ix_roster_league_team', 'team_rosters', ['league_key', 'team_key'], unique=False)
    op.create_index(op.f('ix_team_rosters_league_key'), 'team_rosters', ['league_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_rosters_league_key'), table_name='team_rosters')
    op.drop_index('ix_roster_league_team', table_name='team_rosters')
    op.drop_index('ix_roster_league_player', table_name='team_rosters')
    op.drop_table('team_rosters')
    # ### end Alembic commands ###
