"""add elevation_off to player_ratings

Revision ID: 754dc8c4172f
Revises: a1d6ebe58231
Create Date: 2026-06-13 22:22:32.476429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754dc8c4172f'
down_revision: Union[str, Sequence[str], None] = 'a1d6ebe58231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_ratings', sa.Column('elevation_off', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_ratings', 'elevation_off')
    # ### end Alembic commands ###
