"""goalie_starts append only observation log

Turns the table from one mutable row per (game, goalie) into an append-only
log of observations keyed by when they were seen. Without `observed_at`,
a backtest reads the settled game-day confirmation when replaying a
decision made days earlier, and goalie streaming shows a large fake edge.

The table is empty at the time of this migration, so `observed_at` can be
added NOT NULL directly with no backfill.

Revision ID: 7e206a9c3871
Revises: c4e1a9b7d302
Create Date: 2026-08-02 21:53:35.142863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e206a9c3871'
down_revision: Union[str, Sequence[str], None] = 'c4e1a9b7d302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goalie_starts', sa.Column('observed_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('uq_goalie_start_game_player'), 'goalie_starts', type_='unique')
    op.create_index('ix_goalie_starts_game_observed', 'goalie_starts', ['game_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_goalie_starts_observed_at'), 'goalie_starts', ['observed_at'], unique=False)
    op.create_unique_constraint('uq_goalie_start_observation', 'goalie_starts', ['game_id', 'nhl_id', 'observed_at', 'source'])
    op.drop_column('goalie_starts', 'first_seen_at')
    op.drop_column('goalie_starts', 'scraped_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goalie_starts', sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('goalie_starts', sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_goalie_start_observation', 'goalie_starts', type_='unique')
    op.drop_index(op.f('ix_goalie_starts_observed_at'), table_name='goalie_starts')
    op.drop_index('ix_goalie_starts_game_observed', table_name='goalie_starts')
    op.create_unique_constraint(op.f('uq_goalie_start_game_player'), 'goalie_starts', ['game_id', 'nhl_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('goalie_starts', 'observed_at')
    # ### end Alembic commands ###
