"""add confirmation tier to goalie_starts

Revision ID: 8ad0fa8aa636
Revises: 937576d6a631
Create Date: 2026-08-02 19:19:30.529797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad0fa8aa636'
down_revision: Union[str, Sequence[str], None] = '937576d6a631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goalie_starts', sa.Column('confirmation', sa.String(length=20), nullable=True))
    op.add_column('goalie_starts', sa.Column('first_seen_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_goalie_start_game_player', 'goalie_starts', ['game_id', 'nhl_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_goalie_start_game_player', 'goalie_starts', type_='unique')
    op.drop_column('goalie_starts', 'first_seen_at')
    op.drop_column('goalie_starts', 'confirmation')
    # ### end Alembic commands ###
