"""add goalie_game_log table

Revision ID: 937576d6a631
Revises: 71b2c6362b26
Create Date: 2026-08-02 19:12:32.646530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937576d6a631'
down_revision: Union[str, Sequence[str], None] = '71b2c6362b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('goalie_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('is_start', sa.Boolean(), nullable=False),
    sa.Column('is_relief', sa.Boolean(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('toi_seconds', sa.Integer(), nullable=True),
    sa.Column('played_full_game', sa.Boolean(), nullable=True),
    sa.Column('decision', sa.String(length=3), nullable=True),
    sa.Column('shutout', sa.Boolean(), nullable=False),
    sa.Column('team_score', sa.Integer(), nullable=True),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.Column('shots_against', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('fenwick_against', sa.Integer(), nullable=True),
    sa.Column('empty_net_ga_team', sa.Integer(), nullable=True),
    sa.Column('xga', sa.Float(), nullable=True),
    sa.Column('gsax', sa.Float(), nullable=True),
    sa.Column('hd_shots_against', sa.Integer(), nullable=True),
    sa.Column('hd_goals_against', sa.Integer(), nullable=True),
    sa.Column('hd_xga', sa.Float(), nullable=True),
    sa.Column('md_shots_against', sa.Integer(), nullable=True),
    sa.Column('md_goals_against', sa.Integer(), nullable=True),
    sa.Column('md_xga', sa.Float(), nullable=True),
    sa.Column('ld_shots_against', sa.Integer(), nullable=True),
    sa.Column('ld_goals_against', sa.Integer(), nullable=True),
    sa.Column('ld_xga', sa.Float(), nullable=True),
    sa.Column('ev_shots_against', sa.Integer(), nullable=True),
    sa.Column('ev_goals_against', sa.Integer(), nullable=True),
    sa.Column('pk_shots_against', sa.Integer(), nullable=True),
    sa.Column('pk_goals_against', sa.Integer(), nullable=True),
    sa.Column('pp_shots_against', sa.Integer(), nullable=True),
    sa.Column('pp_goals_against', sa.Integer(), nullable=True),
    sa.Column('fpts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'goalie_id', name='uq_goalie_game')
    )
    op.create_index(op.f('ix_goalie_game_log_game_date'), 'goalie_game_log', ['game_date'], unique=False)
    op.create_index('ix_goalie_game_log_goalie_date', 'goalie_game_log', ['goalie_id', 'game_date'], unique=False)
    op.create_index('ix_goalie_game_log_team_date', 'goalie_game_log', ['team_id', 'game_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goalie_game_log_team_date', table_name='goalie_game_log')
    op.drop_index('ix_goalie_game_log_goalie_date', table_name='goalie_game_log')
    op.drop_index(op.f('ix_goalie_game_log_game_date'), table_name='goalie_game_log')
    op.drop_table('goalie_game_log')
    # ### end Alembic commands ###
