"""add player_ratings table

Revision ID: a1d6ebe58231
Revises: f214b6fb070a
Create Date: 2026-06-13 18:48:52.280595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d6ebe58231'
down_revision: Union[str, Sequence[str], None] = 'f214b6fb070a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('seasons', sa.String(length=64), nullable=False),
    sa.Column('rating_off', sa.Float(), nullable=False),
    sa.Column('rating_def', sa.Float(), nullable=True),
    sa.Column('toi_minutes', sa.Float(), nullable=False),
    sa.Column('percentile_off', sa.SmallInteger(), nullable=True),
    sa.Column('percentile_def', sa.SmallInteger(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'model_version', 'seasons', name='uq_player_rating')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_ratings')
    # ### end Alembic commands ###
