"""add shift_segments table

Revision ID: f214b6fb070a
Revises: f0f56db6effc
Create Date: 2026-06-13 17:44:03.568404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f214b6fb070a'
down_revision: Union[str, Sequence[str], None] = 'f0f56db6effc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('start_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('end_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('duration_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('situation', sa.String(length=8), nullable=False),
    sa.Column('score_state', sa.SmallInteger(), nullable=False),
    sa.Column('home_skater_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('away_skater_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('home_xgf', sa.Float(), nullable=False),
    sa.Column('away_xgf', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_segments_game_period', 'shift_segments', ['game_id', 'period'], unique=False)
    op.create_index('ix_shift_segments_situation', 'shift_segments', ['situation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shift_segments_situation', table_name='shift_segments')
    op.drop_index('ix_shift_segments_game_period', table_name='shift_segments')
    op.drop_table('shift_segments')
    # ### end Alembic commands ###
